version: '3'

services:
  # nginx:
  #   container_name: sample_nginx
  #   image: sample_nginx
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.nginx
  #   ports:
  #     - "80:80"

  nginx:
    container_name: sample_nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf.d:/etc/nginx/conf.d

  django:
    container_name: sample_django
    build: .
    ports:
      - "8000:8000"
